### ISSUE TITLE
Cannot set launch info during runtime

### ISSUE THREAD

**Issue by nabsofken** [reportportal/agent-net-specflow#18]
I have the following code: 

```
[BeforeTestRun(Order = 0)]
		public static void BeforeTestRunPart()
		{
            ReportPortalAddin.BeforeRunStarted += ReportPortalAddin_BeforeRunStarted;
		}

        private static void ReportPortalAddin_BeforeRunStarted(object sender, RunStartedEventArgs e)
        {
            // Adding feature tag on runtime

            e.Launch.Name = "test launch";
            e.Launch.Mode = ReportPortal.Client.Models.LaunchMode.Default;
            e.Launch.Description = "Test";
        }
```

When I run my tests I only see the launch info set in the App.Config file in the RP server. If I comment out the launch line from App.Config, I don't see the run on the RP server.
using specflow 2.2, nunit 3.7

**Comment by aliaksandrbasau** [comment]
I think I know what is the cause of the issue. Your BeforeTestRun hook is executed after a launch is created. It happens because the BeforeTestRun hook from plugin has lower order (-20000) and it's executed before yours.
It was done intentionally in order to see that there is something wrong with the launch if the hook throws an exception for any reason or in case if you want to log messages from the hook.

Please try to set hook order to -30000:
[BeforeTestRun(Order = -30000)]

I am going to update the example. Thanks for reporting the issue!
