### ISSUE TITLE
Agent installation questions

### ISSUE THREAD

**Issue by Free1man** [reportportal/agent-net-specflow#29]
The Problem: Data about my test runs are not populated in ReportPortal server.

My actions:
1) I'm running ReportPortal in Docker container via Docker toolbox.
2) I can access the portal by IP:8080 and log in.
3) I have created the New Project in Report portal.
4) I have installed ReportPortal.SpecFlow to my project. (app.config was updated and ReportPortal.SpecFlowPlugin.dll.config was created)
5) I have updated ReportPortal.SpecFlowPlugin.dll.config to my params.
6) I run my Specflow tests.

ERROR: Nothing in Report portal :( What I'm doing wrong?

My packges:
`  <package id="NUnit" version="3.10.1" targetFramework="net452" />
  <package id="ReportPortal.Client" version="2.0.1" targetFramework="net452" />
  <package id="ReportPortal.Shared" version="2.0.0" targetFramework="net452" />
  <package id="ReportPortal.SpecFlow" version="1.2.3" targetFramework="net452" />
  <package id="SpecFlow" version="2.3.1" targetFramework="net452" />
  <package id="SpecFlow.CustomPlugin" version="2.3.1" targetFramework="net452" />
  <package id="SpecFlow.NUnit" version="2.3.1" targetFramework="net452" />
`

**Comment by aliaksandrbasau** [comment]
@Free1man Currently, because of the async nature of the agent, when an exception occurs it will not be visible to the main thread.
I suspect that there is something wrong with your configuration files.
There are ways to get more information about the issue.
1. Using Fiddler.
Launch Fiddler and try to reproduce the issue.
If you don't see any requests, try to force the agent to use the proxy server. It can be done by modifying the configuration file - adding `proxy` section:
```
  <reportPortal enabled="true">
    <server url="https://{SERVER}:{PORT}/api/v1/" project="default_project">
      <authentication username="default" password="aa19555c-c9ce-42eb-bb11-87757225d535" />
	  <proxy server="localhost:8888"></proxy>
    </server>
    <launch name="SpecFlow Demo Launch" debugMode="true" tags="t1,t2" />
  </reportPortal>
```
2. By logging all unhandled exceptions. I have to admit that I didn't use this approach in this particular context but, I think, it should work.
Use the following code to define handlers and to register them.
```
static void UnhandledExceptionHandler(object sender, UnhandledExceptionEventArgs e)
{
	Console.WriteLine(e.ExceptionObject as Exception);
}

static void FirstChanceHandler(object source, FirstChanceExceptionEventArgs e)
{
	Console.WriteLine(e.Exception);
}
```

```
AppDomain.CurrentDomain.FirstChanceException += FirstChanceHandler;
AppDomain.CurrentDomain.UnhandledException += UnhandledExceptionHandler; 
```

Please let me know if it helped to find the cause of the issue.

@nvborisenko and I are aware about the issue that the exceptions are not visible to the end user, and I am going to fix it in a couple of weeks.

**Comment by nvborisenko** [comment]
@Free1man I guess launches my be found on "Debug" tab (left panel).

**Comment by nvborisenko** [comment]
@Free1man did you resolve your issue?
