### ISSUE TITLE
Logging step result

### ISSUE THREAD

**Issue by fasterfish** [reportportal/agent-net-specflow#3]
At any step of feature i do Console.WriteLine("Something"), but the result of this action is not displayed on the portal.

Example Method:

>[Given("I have entered (.*) into the calculator")]
public void GivenIHaveEnteredSomethingIntoTheCalculator(int number)
{ 
Console.WriteLine("This is sparta!!!!!!");
}

Actual Result:
![screenshot_1](https://cloud.githubusercontent.com/assets/18389889/21148981/c86cf118-c17b-11e6-97a8-eb9bc824460d.png)

Maybe I'm doing something wrong?

**Comment by aliaksandrbasau** [comment]
You will need to use one of logger libraries instead of writing messages directly to Console. There are a number of popular logging libraries that are supported - System.Diagnostics.TraceListener, nlog, log4net. And there are Report Portal libraries for integration with these loggers. You can find them under https://github.com/reportportal. Their repository names start with "logger-net-". The integration libraries are also installed as NuGet packages. Please check the repository README for details about integration.

**Comment by fasterfish** [comment]
Thank you. I added Nlog and logger-net-nlog into the project - it works fine.

![screenshot_2](https://cloud.githubusercontent.com/assets/18389889/21169516/bc0b7436-c1de-11e6-89f2-44e25fb37e71.png)
